### ISSUE TITLE
How to renderering mesh  using  MVP matrices  like openGL?

### ISSUE THREAD

**Issue by ForrestPi** [o0Helloworld0o-ustc/ECCV2022_WCPA_track2#3]
I am confused about how to render the  mesh  under perspective projection on the whole image？
could you provide a computing formula of how to calac MVP matrics？
could you provide the pinhole camera of focal length  or FOV setting？
Thanks

**Comment by o0Helloworld0o** [comment]
Hi, ForrestPi. The rendering pipeline provided in visualization.ipynb follows the OpenGL format. The core formula is "verts = verts_homo @ R_t @ M_proj @ M1" (see visualization.ipynb for more details) in which the face vertices are transformed successively from world space, to camera space, to NDC space, to image space. Note that the original face vertices are already in world space indicating that the transformation from face's local coordinate space into world space is omitted. We have processed the data so that all instances use the same M_proj matrix and M1 matrix. The focal length and FOV can be derived from the OpenGL projection matrix M_proj.
M_proj = [
  1.57443701, 0,          0,            0
  0,          1.57443701, 0,            0
  0,          0,          -0.99999976, -1
  0,          0,          -0.001,       0
]
1/tan(FOV/2) = 1.57443701
img_size = 800
=> FOV = arctan(1/1.57443701) * 2 = 1.13(rad) = 64.84(deg)
=> focal_length = 1/tan(FOV/2) * (0.5*img_size) = 1.57443701 * 0.5 * 800 = 629.77

**Comment by XYZ-qiyh** [comment]
Hello @o0Helloworld0o , thanks for your excellent project.
I have some question about the `R_t` in ground-truth info file. One example of the `R_t` is shown as follows:
```
[[ 0.77431804 -0.09024301 -0.6263289   0.        ]
 [-0.01554852  0.9867669  -0.16139811  0.        ]
 [ 0.6326057   0.13471198  0.76266825  0.        ]
 [ 0.0217499  -0.00894303 -0.66901565  1.        ]]
```
I guess the `R_t` may be stored in OpenGL format. But in computer vision, the camera pose is stored as 
```
[R, t]
[0, 1]
```
My question is how to convert the computer vision camera pose to OpenGL format.
Looking forward to your reply.
Many thanks!

**Comment by XYZ-qiyh** [comment]
@o0Helloworld0o @o0Helloworld0o-ustc  Thanks for your amazing project!
If I want to use this project to test custom photos, how to adjust the **M_proj** and **M1** matrix?

**Comment by o0Helloworld0o** [comment]
Hi, XYZ-qiyh. For customized facial images, you should know the exact camera intrinsics. First you should fill the image into a square so that the aspect ratio is 1. According to the camera intrinsics, if the principal point is not located in the image center, the image should be padded so that the principal point is exactly located in the image center. This project specifies a standard FOV=64.84 (deg), which means you need to further crop or pad the image to achieve the specified FOV. In this way, M_Proj matrix can remain unchanged. As for M1 matrix, you can set it according to your final image size. I hope it will help you.

**Comment by XYZ-qiyh** [comment]
> Hi, XYZ-qiyh. For customized facial images, you should know the exact camera intrinsics. First you should fill the image into a square so that the aspect ratio is 1. According to the camera intrinsics, if the principal point is not located in the image center, the image should be padded so that the principal point is exactly located in the image center. This project specifies a standard FOV=64.84 (deg), which means you need to further crop or pad the image to achieve the specified FOV. In this way, M_Proj matrix can remain unchanged. As for M1 matrix, you can set it according to your final image size. I hope it will help you.

Thanks for your detailed explanation. 🚀
