### ISSUE TITLE
About the Datasets

### ISSUE THREAD

**Issue by VictoryTianke** [o0Helloworld0o-ustc/ECCV2022_WCPA_track2#4]
Thx for your great work!
Unfortunately, I missed the registration time of this WCPA competition. May I get the datasets used for training&valid in the competition.

Thx again!

**Comment by o0Helloworld0o** [comment]
Hi! Thank you for your interest in WCPA challenges. The copyright owner of the dataset we use in this challenger is Speechocean ([https://www.speechocean.com](https://en.speechocean.com/)). According to our agreement with Speechocean, because face data is sensitive, the dataset will no longer be available for download as the challenge ends. We plan to write a paper with this dataset, and then more data will be released than this challenge. But it may take a long time to wait until our paper is accepted and published. If you are anxious to use this dataset, you can contact the staff of the Speechocean by yourself (wcpa-service@speechocean.com). Thank you!
